FROM ubuntu:18.04
ENV LANG C.UTF-8
RUN apt-get update && apt-get -y install python3 python3-pip perl wget
RUN pip3 install numpy textgrid

RUN wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB | apt-key add - && \
    echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list && \
    apt-get update && \
    apt-get -y install intel-mkl-64bit-2019.5-075

WORKDIR /home/ubuntu/trained_kaldi_models
COPY trained_kaldi_models ./

COPY work/server.py ./
EXPOSE 8080
CMD python3 server.py
